---
title: "Overview"
---

The main goals of this class are to help you design, critique, code, and run rigorous, valid, and feasible evaluations of educational programs. Each type of assignment in this class is designed to help you achieve one or more of these goals.

For more detailed instructions, please refer to the pages for the [reading reactions](/assignment/weekly-check-in.qmd), [data-analytic memos](/assignment/dams.qmd), and the [exam](/assignment/exam.qmd). For the [final course project](/assignment/final-project.qmd), you will develop an evalution plan for a new education program that excites you. Throughout the quarter, there will be three milestones related to the evaluation plan. 

As you've seen on the [syllabus](/syllabus/index.html) and [schedule](/schedule/index.html) pages, the assignment dates are as follows.

| Category          | Release date         | Due date            |
|:------------------|:---------------------|:--------------------|
| Survey 1          | Mon, Sep 25 09:00AM  | Sun, Oct 01 11:55PM |
| Milestone 1       |                      | Sun, Oct 08 11:55PM |
| Milestone 2       |                      | Sun, Oct 15 11:55PM |
| DAM 1             | Mon, Oct 16 09:00AM  | Sun, Oct 22 11:55PM |
| DAM 2             | Mon, Oct 23 09:00AM  | Sun, Oct 29 11:55PM |
| Survey 2          | Mon, Oct 30 09:00AM  | Sun, Nov 05 11:55PM |
| DAM 3             | Mon, Nov 06 09:00AM  | Sun, Nov 12 11:55PM |
| DAM 4             | Mon, Nov 13 09:00AM  | Sun, Nov 19 11:55PM |
| Exam              | Tue, Nov 21 02:00PM  | Tue, Nov 21 03:20PM |
| Milestone 3       |                      | Sun, Dec 03 11:55PM |
| Evaluation plan   |                      | Sun, Dec 15 11:55PM |
| Course evaluation |                      | Sun, Dec 15 11:55PM |

All reading reactions are due by 11:55PM on the day before class. All times are in Pacific time.

Also, to recap what you already saw on the [syllabus](/syllabus/index.html) page, here is how each of your various course contributions and assignments contribute to your overall grade. For group assignments, all group members will receive the same grade. All other contributions are graded individually.

| Category                           | Percent of final grade |
|:-----------------------------------|:-----------------------|
| Participation, reading reactions   | 14%                    |
| Data-analytic memos (DAMs)         | 30%                    |
| Exam                               | 25%                    |
| Milestones 1-3                     | 2% each                |
| Your evaluation plan               | 25%                    |

:::{.callout-note}
## Grace policy

When calculating the final DAM portion of the overall grade, I will drop the lowest score and use the remaining scores. Thus, if you have an emergency that forces you to miss one submission, your grade will not be severely affected.

:::

All grades will be posted through Canvas. 

**Bump-up policy**: I reserve the right to "bump up" the grades of students who have made valuable contributions to the course in the in-person course and discussions/Slack. This also applies to students who show tremendous progress and growth over the quarter. 

Please refer to the [syllabus](/syllabus/index.html) page for the course policies. 
