---
title: "Measurement and data collection"
date: "2023-10-05"
---

## Readings

- {{< fa book >}} Chapter 5 in *Running Randomized Evaluations* [@glennerster_running_2013]
- {{< fa arrow-up-right-from-square >}} Kopper, Sarah, and Katie Parry. ["Introduction to measurement and indicators,"](https://www.povertyactionlab.org/resource/introduction-measurement-and-indicators) *The Abdul Latif Jameel Poverty Action Lab (J-PAL) *, February 2022.

## Audio

Listen to the following news report on New York City Mayor Eric Adams' new plan to curb gun violence. 

- {{< fa podcast >}} WNYC, ["NPR News,"](https://canvas.eee.uci.edu/files/23578134/) August 1, 2023

Think: 

1. What are the indicators mentioned? 
2. What indicators does the clip mention, and how do they relate to the program's Theory of Change? 
3. A friend of yours just heard these news and tells you *"New York City tries to measure the effects of its new anti-gun violence program by counting the number of new trees planted in the city."* Now that you've listened to the same news clip, what do you tell your friend? 

Optional: Instead of today's reading reaction, you may also submit a re-write of this news clip. Start after "some experts are questioning how officials will measure whether it's working." 

This is not needed for class but, if you are interested in the plan discussed on the news, you can find the document [here](https://www.nyc.gov/assets/home/downloads/pdf/press-releases/2023/Blueprint-Community-Safety.pdf). 

## Slides

On the day of class, you will find my slides on Canvas. 
